#!/usr/bin/env sh
if command -v nodemcu-uploader; then
  uploader=nodemcu-uploader
else
  uploader=python nodemcu-uploader/nodemcu-uploader.py
fi
$uploader node info
$uploader $* upload init.lua httpserver.lua rgb.lua index.html rgb.html
$uploader node restart
